version: '3.7'
services:
  postgres:
    image: postgres:13.4
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root54321
      POSTGRES_DB: postgresDb
